# Odin Agent Application Configuration
# =====================================
# This file defines the complete configuration for an Odin agent.
# It supports multiple protocols and can be started with:
#   odin serve --config app.yaml

name: weather-assistant
description: An AI-powered weather and calendar assistant
version: "1.0.0"

# Server Configuration
# --------------------
server:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"  # React frontend
    - "http://localhost:5173"  # Vite frontend
    - "*"  # Allow all (for development)

# Protocol Endpoints
# ------------------
# Define which protocols to expose. Multiple protocols can be enabled simultaneously.
protocols:
  # AG-UI: For CopilotKit and other generative UI frontends
  - type: ag-ui
    enabled: true
    path: /copilotkit  # CopilotKit expects this path

  # A2A: For agent-to-agent communication
  - type: a2a
    enabled: true
    path: /a2a

  # MCP: For Claude Desktop (requires separate stdio server)
  - type: mcp
    enabled: false

# LLM Configuration (optional - used by agent engine)
# ---------------------------------------------------
llm:
  provider: openai
  model: gpt-4
  api_key_env: OPENAI_API_KEY
  temperature: 0.7

# Agent Engine (optional - for multi-agent orchestration)
# -------------------------------------------------------
# If not specified, tools are exposed directly without agent orchestration
# agent:
#   type: crewai
#   config:
#     verbose: true
#     max_iterations: 10

# Plugins
# -------
# Define which plugins to load. Each plugin provides tools.
plugins:
  - name: weather
    module: plugins.weather
    enabled: true
    config: {}

  - name: calendar
    module: plugins.calendar
    enabled: true
    config: {}

# Metadata
# --------
metadata:
  author: "Your Name"
  repository: "https://github.com/yourname/yourproject"
